### ISSUE TITLE
Use cases for Underscore::constant()

### ISSUE THREAD

**Issue by p810** [adhocore/underscore#8]
I'm curious about when [`Underscore::constant()`](https://github.com/adhocore/underscore/blob/master/src/Underscore.php#L36) would be applicable? I'm out of the loop and have never seen something like this implemented before (to my knowledge). Thanks!

**Comment by adhocore** [comment]
for example you have to pass in a dependency resolver as callable (read: closure fn) and it is very likely that this callable is invoked() in many places causing that dependency to be newly instantiated everytime. 
however if you passed in constant resolver, no matter how many times the resolver callable is invoked you will get same instance.

```php
class A
{
  function dbResolver(callable $fn)
  {
    $db = $fn();
  }
}

class B
{
  function dbResolver(callable $fn)
  {
    $db = $fn();
  }
}

// constant resolver
$dbResolver = underscore()->constant(new Db($dsn));

// send resolver out in the wild
(new A)->dbResolver($dbResolver);
(new B)->dbResolver($dbResolver);

// A, B ... Z will all always have same instance of `Db`
```
